### ISSUE TITLE
Sudo necessity in ctest when update_VM.sh with option to install prerequisites

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SyneRBI_VM#160] opened 2020-05-04 09:08 UTC
I tested the PR for the option to install prerequisites.
The script went through and no errors occured.

However, when I went to run the tests 
```
cd ~/devel/buildVM/buils/SIRF/build
ctest -VV -R 
```
then I receive the error
```
2: Test command: /usr/bin/python "-m" "nose" "--with-coverage" "--cover-package=sirf.Gadgetron" "src/xGadgetron/pGadgetron/"
2: Test timeout computed to be: 10000000
2: ERROR: HDF5 Error in ../../../src/H5FDsec2.c, line 348: unable to open file: name = 'tmp_1_1588583252375.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 242
2: ERROR: HDF5 Error in ../../../src/H5FD.c, line 812: open failed
```
This Permission denied error does not happen when I run 
```
sudo ctest -VV -R 
```
instead.

**Comment by KrisThielemans** [comment] 2020-05-04 09:19
hmmm. this is very strange. Are you sure you haven't run `sudo update_VM.sh ...` at some point? I cannot see why the update script would do this (but then again, all bugs result in weird behaviour!)

**Comment by johannesmayer** [comment] 2020-05-04 09:21
ok maybe i did run sudo update_VM.sh

**Comment by rijobro** [comment] 2020-05-04 09:21
I'll download a fresh 2.1 and see what happens

**Comment by rijobro** [comment] 2020-05-04 10:43
Sorry for putting an unrelated error into this issue, I'll create a new issue if the answer isn't trivial.

```
fatal: ambiguous argument 'rel_4.0.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
From https://github.com/UCL/STIR
   8942f4e6..2a799b93  Siemens_mCT_additions -> origin/Siemens_mCT_additions
   fd8b7555..dcfda6b1  master                -> origin/master
 * [new branch]        release_4             -> origin/release_4
 * [new branch]        release_4.0           -> origin/release_4.0
 * [new tag]           rel_4.0.0             -> rel_4.0.0
 * [new tag]           stir_rel_4.0.0        -> stir_rel_4.0.0
error: pathspec 'rel_4.0.1' did not match any file(s) known to git.
CMake Error at /home/sirfuser/devel/buildVM/builds/STIR/tmp/STIR-gitupdate.cmake:147 (message):
  Failed to checkout tag: 'rel_4.0.1'
```

I ran cmake in `build_VM` and set the STIR tag to `release_4`, then re-ran the update script and got the same error. Suppose I could modify the default STIR tag in `version_config.cmake`, although that might get reset by the update script, too.

**Comment by johannesmayer** [comment] 2020-05-04 10:47
Didn't that happen last Friday as well, because the `git fetch` needed to be run with `git fetch --tag`?

**Comment by KrisThielemans** [comment] 2020-05-04 10:49
yup. I thought I fixed that...

**Comment by KrisThielemans** [comment] 2020-05-04 10:51
oh. maybe the problem is that version_config.cmake should specify `origin/rel_4.0.1`

**Comment by rijobro** [comment] 2020-05-04 13:12
Same error. I guess it's just not doing a `git fetch`?

**Comment by KrisThielemans** [comment] 2020-05-04 16:23
can you create a snapshot (such that you can go back), and then do a `git fetch` by hand, and see what happens?

**Comment by rijobro** [comment] 2020-05-04 16:31
I ran `git fetch --tags` earlier (didn't think to create a snapshot, sorry) and then compilation was fine and all ctests passed.

**Comment by KrisThielemans** [comment] 2020-05-04 17:20
Closing this and transferred discussion

**Closed by KrisThielemans** 2020-05-04 17:20 UTC
